name: Prepare javascript / HTML / CSS assets
description: Builds and copies the assets into the Java and Ruby package folders
runs:
  using: "composite"
  steps:
    - name: with Node.js 16 on ubuntu-latest
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 22.x
        cache: "npm"
        cache-dependency-path: javascript/package-lock.json

    - name: build javascript assets
      run: make prepare
      shell: bash
