name: Prepare javascript / HTML / CSS assets
description: Builds and copies the assets into the Java and Ruby package folders
runs:
  using: "composite"
  steps:
    - name: with Node.js 16 on ubuntu-latest
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22.x
        cache: "npm"
        cache-dependency-path: javascript/package-lock.json

    - name: build javascript assets
      run: make prepare
      shell: bash
